version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20
    steps:
      - checkout
      - run: npm ci
      - run: node app.js
      - run: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
